### ISSUE TITLE
Example not working properly using Supabase's oAuth 

### ISSUE THREAD

**Issue by andrejbroncek** [ruanmartinelli/supabase-auth-react#1]
Hello, first of all, thanks a lot for an amazing example of using protected routes with Supabase. I tried applying your code to my project, and while it works flawlessly for regular login, it does not work for oAuth. Obviously, I had to rewrite `Auth.js` a bit, to support provider: `signIn: (data, options) => supabase.auth.signIn(data, options),`. Other than that, I expected it to work without any issues with this method:

```  
  async function handleOAuthLogin(provider) {
    const { error } = await supabase.auth.signIn(
      { provider },
      {
        redirectTo: 'http://localhost:3000/',
      }
    );
    if (error) return setHelperText({ error: true, text: error.message });
  }
```

Unfortunately, I always get redirected back to login. It seems like Supabase's redirect happens before the `onAuthStateChange` in `Auth.js` is triggered. I am stuck on this, I've literally tried everything that came to my mind with no avail. Would you please be so kind and try to assist me? Thank you very much!

**Comment by ruanmartinelli** [comment]
Hey Andrej, I'm happy that the repo helped you get started!

I didn't try it with oAuth yet, so I'm not sure right what the issue can be in your example from the top of my head. I also don't have a lot of bandwidth at the moment to debug it. 

Have you tried reaching out to the folks from Supabase? They're very helpful and I'm sure you'll get some support. And if there's something wrong in the code here, please do let me know!

**Comment by ruanmartinelli** [comment]
Closing this one, hope you found a solution!
